

obj-$(CONFIG_CMD_FPU) += fpu.o
obj-$(CONFIG_CMD_NUC_TST) += standalone_test.o
obj-$(CONFIG_CMD_MCU) += mcu_updater.o
obj-$(CONFIG_CMD_CACHE_PERF) += cache_perf.o
obj-$(CONFIG_CMD_CACHE_TEST) += cache_test.o
obj-$(CONFIG_CMD_GFX) += gfx_test.o
obj-$(CONFIG_CMD_DDR_ECC) += ddr_ecc.o
obj-$(CONFIG_CMD_NPCM_REGINFO) += npcm_reg_info.o
