#Common TextBase address
#CONFIG_SYS_TEXT_BASE = 0x01400000

#Common include search pathes
PLATFORM_CPPFLAGS += -I$(srctree)/
PLATFORM_CPPFLAGS += -I$(srctree)/board/nuvoton/common/BMC_HAL/Chips
PLATFORM_CPPFLAGS += -I$(srctree)/board/nuvoton/common/SWC_DEFS
PLATFORM_CPPFLAGS += -I$(srctree)/board/nuvoton/PolegSVB

# We don't use LIBC in this project
PLATFORM_CPPFLAGS += -DNO_LIBC

#Setting board depending flags
PLATFORM_CPPFLAGS += -DBOARD_NAME=PolegSVB
PLATFORM_CPPFLAGS += -DEXTERNAL_INCLUDE_FILE=\"$(srctree)/board/nuvoton/common/nuvoton_hal.h\"

#Common optimizations flags
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRCPY
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRNCPY
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRCAT
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRNCAT
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRCMP
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRNCMP
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRCHR
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRRCHR
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRLEN
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRNLEN
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRDUP
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRSPN
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRPBRK
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRTOK
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRSEP
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRSWAB
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_MEMSET
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_BCOPY
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_MEMCPY
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_MEMMOVE
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_MEMCMP
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_MEMSCAN
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_STRSTR
#PLATFORM_CPPFLAGS += -D__HAVE_ARCH_MEMCHR





