
#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= nuvoton_aic.o nuvoton_serial.o nuvoton_eth.o nuvoton_timer.o nuvoton_flash.o nuvoton_init.o nuvoton_low_level.o
obj-$(CONFIG_USB_HOST)	+= nuvoton_usb.o

