/*--------------------------------------------------------------------------
 * Copyright (c) 2009-2010 by Nuvoton Technology Israel
 * All rights reserved.
 *--------------------------------------------------------------------------*/

/*------------------------------------------------------------------------*/
/*-------------------------   Include files   ----------------------------*/
/*------------------------------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <PolegTemplate.h>
#include "../Arbel.h"
//#include "GIC/gic_API.h"
#include "CoreUtility.h"
#include "Common.h"




void	ID_PrintChipID						(void)
{
	LogTitle("CHIP ID\n");
}

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        CLK_GetTimeStamp                                                                       */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         Current time stamp                                                                     */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*---------------------------------------------------------------------------------------------------------*/
void  CLK_GetTimeStamp(DWORD time_quad[2])
{
	DWORD Seconds;
	DWORD RefClocks;




	do
	{
		Seconds = READ_REG(SECCNT);
		RefClocks = (READ_REG(CNTR25M)) & 0x01FFFFFF;
	} while (READ_REG(SECCNT) != Seconds);

	time_quad[0] = RefClocks;
	time_quad[1] = Seconds;
}



/*---------------------------------------------------------------------------------------------------------*/
/* Function:        CLK_Delay_Since                                                                        */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  microSecDelay -  number of microseconds to delay since t0_time. if zero: no delay.     */
/*                  t0_time       - start time , to measure time from.                                     */
/*                                                                                                         */
/* Returns:                                                                                                */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  get a time stamp, delay microSecDelay from it. If microSecDelay has already passed     */
/*                  since the time stamp , then no delay is executed. returns the time that elapsed since  */
/*                  t0_time .                                                                              */
/*---------------------------------------------------------------------------------------------------------*/
#define EXT_CLOCK_FREQUENCY_MHZ 25
#define  CNTR25M_ACCURECY                 EXT_CLOCK_FREQUENCY_MHZ 
#define _1Hz_           1UL
#define _1KHz_          (1000 * _1Hz_ )
#define _1MHz_          (1000 * _1KHz_)
#define _1GHz_          (1000 * _1MHz_)

DWORD CLK_Delay_Since(DWORD microSecDelay, DWORD t0_time[2])
{




	DWORD iUsCnt2[2];
	DWORD timeElapsedSince;  // Acctual delay generated by FW
	DWORD minimum_delay = (microSecDelay * EXT_CLOCK_FREQUENCY_MHZ) + CNTR25M_ACCURECY; /* this is equivalent to microSec/0.64 + minimal tic length.*/


	do
	{
		CLK_GetTimeStamp(iUsCnt2);
		timeElapsedSince = ((EXT_CLOCK_FREQUENCY_MHZ * _1MHz_) * (iUsCnt2[1] - t0_time[1])) + (iUsCnt2[0] - t0_time[0]);
	} while (timeElapsedSince < minimum_delay);

	/*-----------------------------------------------------------------------------------------------------*/
	/* return elapsed time                                                                                 */
	/*-----------------------------------------------------------------------------------------------------*/
	return (DWORD)(timeElapsedSince / EXT_CLOCK_FREQUENCY_MHZ);
}




	




