#---------------------------------------------------------------------------------------------------------#
#	Nuvoton Technology Corporation Confidential 														  #
#																										  #
#	Copyright (c) 2016 by Nuvoton Technology Corporation	     										  #
#	SPDX-License-Identifier:	GPL-2.0+																  #
#---------------------------------------------------------------------------------------------------------#

obj-$(CONFIG_NUVOTON_POLEG_SHA)	+= nuvoton_sha.o
obj-$(CONFIG_NUVOTON_POLEG_RNG) += nuvoton_rng.o