# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com

obj-$(CONFIG_EXYNOS_ACE_SHA)	+= ace_sha.o
obj-$(CONFIG_NPCMX50_RNG) += npcmX50_rng.o
obj-$(CONFIG_NPCMX50_AES) += npcmX50_aes.o
obj-$(CONFIG_NPCMX50_SHA) += npcmX50_sha.o
obj-y += rsa_mod_exp/
obj-y += fsl/
