# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com

obj-$(CONFIG_EXYNOS_ACE_SHA)	+= ace_sha.o
obj-$(CONFIG_NPCM750_RNG) += npcm750_rng.o
obj-$(CONFIG_NPCM750_AES) += npcm750_aes.o
obj-y += rsa_mod_exp/
obj-y += fsl/
