# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com

obj-$(CONFIG_EXYNOS_ACE_SHA)	+= ace_sha.o
obj-$(CONFIG_NPCM_AES) += npcm_aes.o
obj-$(CONFIG_NPCM_SHA) += npcm_sha.o
obj-y += rsa_mod_exp/
obj-y += fsl/
